# snake.yml (Place in .github/workflows/snake.yml)
name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: your-username  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7
        with:
          branch: output
          message: 'Generate Snake'